
var translationPL_En = {
    "Lista kanałów": "Channels list",
    "System informacyjny portalu silesia.travel": "Silesia Travel Comunication System",
    "Wstecz": "Back",
    "Pobierz kanały": "Get Channels",
    "Ustawienia użytkownika":"User Settings",
    "Konfiguracja ustawiń użytkownika": "Configure users settings",
    "Proszę wybrać jeden z:": "Please select on of: ",
    "Lista postów dla kanału: {0}": "Post List for Channel: {0}",
    "Odśwież": "Refresh",
    "Post z kanału: {0}": "Post from channel: {0}",
    "Błąd": "Error",
    "Nazwa użytkownika": "User name",
    "Adres serwera z kanałami (domyślnie: http://silesia.travel)": "Channels source serwer adress(default: http://silesia.travel)",
    "Język": "Language",
    "Ustawienia": "Settings",
    "Wyświetl w przeglądarce": "Show in browser",
    "Odśwież": "Refresh",
    "Przepraszamy, ale nie udało się załadować informacji o dostępnych kanałach": "Sorry, Can't find information about channels",
    "Przepraszamy, ale nie udało się załadować listy postów dla wybranego kanału": "Sorry, Can't find post list for selected channel",
    "Wybierz sposób defniowania lokalizacji": "Select localization definition method",
    "Nadpisać lokalizację z konfiguracji kanałów ?": "Override localization configuration from channel definition ?",
    "Wybierz miejscowość": "Select place",
    "Wykorzystaj pozycję goegraficzną": "Use geo coordiantes",
    "Adres serwera z kanałami": "Server adress",
    "Konfiguracja lokalizacji": "Localization config",
    "Wybierz Miejscowość": "Select place",
    "Zatwierdź": "Apply",
    "Anuluj": "Cancel",
    "Powrót": "Back",
    "Lista Kanałów": "Channels list",
    "Wybierz Kanał Informacyjny": "Select information channel",
    "Skonfiguruj ustawienia użytkownika": "Configure user settings",
    "Język interfejsu": "Interface language",
    "Lista postów dla kanału:":"Post list for channel:",
    "Post z kanału: ": "Post from channel: ",
    "silesia.travel - Kanały informacyjne": "silesia.travel - Information channels",
    "Wczytywanie":"Loading"

}